{% set version = "2.2.16" %}

package:
  name: moto
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/m/moto/moto-{{ version }}.tar.gz
    sha256: fef15c831b1356b22beeb4f1b4694945597485bdc111039f1b304ab091141444
  - url: https://github.com/spulec/moto/archive/{{ version }}.tar.gz
    sha256: 38556c006a4d98b749ef201e34ccf5615e1dbe97d816125ca6e50a936dc9870b
    folder: github

build:
  number: 0
  noarch: python
  entry_points:
    - moto_server = moto.server:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - jinja2 >=2.10.1
    # we need to bound this since 198 changed some of the api
    - boto3 >=1.9.201
    - botocore >=1.12.201
    - cryptography >=3.3.1
    - requests >=2.5
    - xmltodict
    - werkzeug
    - pyyaml >=5.1
    - pytz
    - python-dateutil >=2.1,<3.0.0
    - python-jose >=3.1.0,<4.0.0
    - docker-py >=2.5.1
    - responses >=0.9.0
    - cfn-lint >=0.4.0
    - flask
    - flask_cors
    - jsondiff >=1.1.2
    - aws-xray-sdk !=0.96,>=0.93
    - sshpubkeys >=3.1.0,<4.0
    - idna >=2.5,<4

test:
  imports:
    - moto
    - moto.acm
    - moto.apigateway
    - moto.autoscaling
    - moto.awslambda
    - moto.batch
    - moto.cloudformation
    - moto.cloudwatch
    - moto.cognitoidentity
    - moto.cognitoidp
    - moto.config
    - moto.core
    - moto.datapipeline
    - moto.dynamodb
    - moto.dynamodb2
    - moto.dynamodbstreams
    - moto.ec2
    - moto.ec2.responses
    - moto.ecr
    - moto.ecs
    - moto.elb
    - moto.elbv2
    - moto.emr
    - moto.events
    - moto.glacier
    - moto.glue
    - moto.iam
    - moto.instance_metadata
    - moto.iot
    - moto.iotdata
    - moto.kinesis
    - moto.kms
    - moto.logs
    - moto.opsworks
    - moto.organizations
    - moto.packages
    - moto.packages.httpretty
    - moto.polly
    - moto.rds
    - moto.rds2
    - moto.redshift
    - moto.resourcegroupstaggingapi
    - moto.route53
    - moto.s3
    - moto.s3bucket_path
    - moto.secretsmanager
    - moto.ses
    - moto.sns
    - moto.sqs
    - moto.ssm
    - moto.sts
    - moto.swf
    - moto.swf.models
    - moto.xray
  requires:
    - pip
    # just for pip check (not actually used) https://github.com/spulec/moto/issues/4573
    - more-itertools
  commands:
    - pip check
    - moto_server --help

about:
  home: http://getmoto.org
  license: Apache-2.0
  summary: A library that allows your python tests to easily mock out the boto library.
  license_family: APACHE
  license_file: LICENSE
  doc_url: http://docs.getmoto.org
  dev_url: https://github.com/spulec/moto

extra:
  recipe-maintainers:
    - johanneskoester
    - mariusvniekerk
    - hajapy
