{% set version = "3.0.3" %}

package:
  name: moto
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/m/moto/moto-{{ version }}.tar.gz
    sha256: fa3fbdc22c55d7e70b407e2f2639c48ac82b074f472b167609405c0c1e3a2ccb
  - url: https://github.com/spulec/moto/archive/{{ version }}.tar.gz
    sha256: 9a890f2f904624c9121e56677c1ea6b68daf0c47d45cc9b98b7628aaa4039445
    folder: github

build:
  number: 0
  noarch: python
  entry_points:
    - moto_server = moto.server:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - jinja2 >=2.10.1
    # we need to bound this since 198 changed some of the api
    - boto3 >=1.9.201
    - botocore >=1.12.201
    - cryptography >=3.3.1
    - requests >=2.5
    - xmltodict
    - werkzeug
    - pyyaml >=5.1
    - pytz
    - python-dateutil >=2.1,<3.0.0
    - python-jose >=3.1.0,<4.0.0
    - docker-py >=2.5.1
    - responses >=0.9.0
    - cfn-lint >=0.4.0
    - flask
    - flask_cors
    - jsondiff >=1.1.2
    - aws-xray-sdk !=0.96,>=0.93
    - sshpubkeys >=3.1.0
    - idna >=2.5,<4
    - graphql-core
    - setuptools
    - importlib_metadata

test:
  imports:
    - moto
    - moto.acm
    - moto.apigateway
    - moto.applicationautoscaling
    - moto.appsync
    - moto.athena
    - moto.autoscaling
    - moto.awslambda
    - moto.batch
    - moto.budgets
    - moto.cloudformation
    - moto.cloudfront
    - moto.cloudwatch
    - moto.codecommit
    - moto.codepipeline
    - moto.cognitoidentity
    - moto.cognitoidp
    - moto.config
    - moto.core
    - moto.datapipeline
    - moto.datasync
    - moto.dax
    - moto.dms
    - moto.dms
    - moto.ds
    - moto.dynamodb
    - moto.dynamodb2
    - moto.dynamodbstreams
    - moto.ec2
    - moto.ec2.responses
    - moto.ec2instanceconnect
    - moto.ecr
    - moto.ecs
    - moto.efs
    - moto.eks
    - moto.elasticache
    - moto.elasticbeanstalk
    - moto.elastictranscoder
    - moto.elb
    - moto.elbv2
    - moto.emr
    - moto.emrcontainers
    - moto.es
    - moto.events
    - moto.firehose
    - moto.forecast
    - moto.glacier
    - moto.glue
    - moto.guardduty
    - moto.iam
    - moto.instance_metadata
    - moto.iot
    - moto.iotdata
    - moto.kinesis
    - moto.kinesisvideo
    - moto.kinesisvideoarchivedmedia
    - moto.kms
    - moto.logs
    - moto.managedblockchain
    - moto.mediaconnect
    - moto.medialive
    - moto.mediapackage
    - moto.mediastore
    - moto.mediastoredata
    - moto.opsworks
    - moto.organizations
    - moto.packages
    - moto.polly
    - moto.ram
    - moto.rds
    - moto.rds2
    - moto.redshift
    - moto.resourcegroups
    - moto.resourcegroupstaggingapi
    - moto.route53
    - moto.route53resolver
    - moto.s3
    - moto.s3bucket_path
    - moto.s3control
    - moto.sagemaker
    - moto.sdb
    - moto.secretsmanager
    - moto.ses
    - moto.sns
    - moto.sqs
    - moto.ssm
    - moto.ssoadmin
    - moto.stepfunctions
    - moto.sts
    - moto.support
    - moto.swf
    - moto.swf.models
    - moto.templates
    - moto.timestreamwrite
    - moto.transcribe
    - moto.utilities
    - moto.wafv2
    - moto.xray
  requires:
    - pip
  commands:
    - pip check
    - moto_server --help

about:
  home: http://getmoto.org
  license: Apache-2.0
  summary: A library that allows your python tests to easily mock out the boto library.
  license_family: APACHE
  license_file: LICENSE
  doc_url: http://docs.getmoto.org
  dev_url: https://github.com/spulec/moto

extra:
  recipe-maintainers:
    - jan-janssen
    - johanneskoester
    - mariusvniekerk
    - hajapy
